/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendatecnologica_izquierdocuevasmartin;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author alumno
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        // Hacer la ventana no redimensionable
        this.setResizable(false);
        // Establecer el tamaño de la ventana 
        this.setSize(1000, 600);
        // Centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);
        cargarUsuarios(); // Cargar usuarios en el combo box al iniciar
        
        // Configurar el comportamiento al cerrar la ventana
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Agregar un evento de cierre para reabrir Tienda
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                abrirVentanaTienda();
            }
        });
    }

    private void abrirVentanaTienda() {
        // Crear una nueva instancia de Tienda y mostrarla
        Tienda tiendaFrame = new Tienda();
        tiendaFrame.setVisible(true);
    }
    
    private void cargarUsuarios() {
        try (Connection conn = ConexionBBDD.getConnection()) {
            // Consulta para obtener los nombres de los usuarios
            String sql = "SELECT nombre FROM usuarios";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            // Vaciar el combo box antes de llenarlo
            boxUsuarios.removeAllItems();

            // Agregar los nombres de los usuarios al combo box
            while (rs.next()) {
                boxUsuarios.addItem(rs.getString("nombre"));
            }

            rs.close();
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void mostrarDatosUsuario(String nombreUsuario) {
    try (Connection conn = ConexionBBDD.getConnection()) {
        // Consulta para obtener los datos del usuario junto con su dirección
        String sql = """
            SELECT u.id, u.nombre, u.email, 
                   d.calle, d.numero, d.ciudad, d.pais
            FROM usuarios u
            LEFT JOIN direccion d ON u.id = d.usuario_id
            WHERE u.nombre = ?;
        """;

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, nombreUsuario);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            // Construir la información del usuario en un formato legible
            StringBuilder datosUsuario = new StringBuilder();
            datosUsuario.append("ID: ").append(rs.getInt("id")).append("\n");
            datosUsuario.append("Nombre: ").append(rs.getString("nombre")).append("\n");
            datosUsuario.append("Email: ").append(rs.getString("email")).append("\n\n");
            datosUsuario.append("Dirección:\n");
            datosUsuario.append("  Calle: ").append(rs.getString("calle")).append("\n");
            datosUsuario.append("  Número: ").append(rs.getInt("numero")).append("\n");
            datosUsuario.append("  Ciudad: ").append(rs.getString("ciudad")).append("\n");
            datosUsuario.append("  País: ").append(rs.getString("pais")).append("\n");

            // Mostrar los datos en el área de texto
            TextAreaDatosUsuario.setText(datosUsuario.toString());
        } else {
            TextAreaDatosUsuario.setText("No se encontraron datos para el usuario seleccionado.");
        }

        rs.close();
        stmt.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxUsuarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDatosUsuario = new javax.swing.JTextArea();
        DatosUsuarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        usuarios.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        usuarios.setForeground(new java.awt.Color(255, 204, 0));
        usuarios.setText("USUARIOS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Seleccione el usuario:");

        boxUsuarios.setBackground(new java.awt.Color(0, 153, 153));
        boxUsuarios.setForeground(new java.awt.Color(204, 255, 204));
        boxUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUsuariosActionPerformed(evt);
            }
        });

        TextAreaDatosUsuario.setColumns(20);
        TextAreaDatosUsuario.setRows(5);
        jScrollPane1.setViewportView(TextAreaDatosUsuario);

        DatosUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DatosUsuarios.setForeground(new java.awt.Color(204, 255, 204));
        DatosUsuarios.setText("Datos del Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DatosUsuarios)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(usuarios)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(usuarios)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DatosUsuarios)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUsuariosActionPerformed
        // TODO add your handling code here:
        // Obtener el usuario seleccionado
        String usuarioSeleccionado = (String) boxUsuarios.getSelectedItem();

        // Mostrar los datos si se seleccionó un usuario válido
        if (usuarioSeleccionado != null && !usuarioSeleccionado.isEmpty()) {
            mostrarDatosUsuario(usuarioSeleccionado);
        }
    }//GEN-LAST:event_boxUsuariosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatosUsuarios;
    private javax.swing.JTextArea TextAreaDatosUsuario;
    private javax.swing.JComboBox<String> boxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel usuarios;
    // End of variables declaration//GEN-END:variables
}
